version: 2

models:

  - name: dim_customers
    description: "Dimension table with customer info and aggregated metrics"
    columns:
      - name: customer_id
        description: "Unique ID of customer"
        tests:
          - not_null
          - unique

      - name: total_orders
        description: "Total number of orders by the customer"
        # tests:
        #   - not_null

  - name: fact_orders
    description: "Fact table containing order-level metrics"
    columns:
      - name: order_id
        description: "Unique ID of the order"
        tests:
          - not_null
          - unique

      - name: customer_id
        description: "Customer who placed the order"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
